-- EnergyApp bootstrap schema for Supabase/Postgres.
-- Intentionally configured for public, anon/no-auth CRUD.

create table if not exists public.projects (
  id text primary key,
  name text not null default 'Untitled Facility',
  location_lat double precision,
  location_lng double precision,
  selected_date text,
  weather_provider text check (weather_provider in ('nrel', 'open_meteo')),
  utility_name text,
  iso_region text,
  timezone text,
  rates_service_type text check (rates_service_type in ('lmp', 'tariff')),
  rates_market_mode text check (rates_market_mode in ('real_time', 'day_ahead', 'tariff')),
  map_state jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assets (
  id text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  asset_type text not null check (asset_type in ('solar', 'wind', 'storage')),
  name text not null default '',
  model jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weather_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  provider text not null default 'nrel' check (provider in ('nrel', 'open_meteo')),
  dataset text not null check (dataset in ('solar', 'wind')),
  date_key text not null,
  source_year integer,
  interval_minutes integer not null,
  wkt text,
  timezone text,
  source text not null default 'weather_proxy',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, provider, dataset, date_key, interval_minutes, source_year)
);

create table if not exists public.rate_series_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  market_mode text not null check (market_mode in ('real_time', 'day_ahead', 'tariff')),
  window_start timestamptz not null,
  window_end timestamptz not null,
  timezone text,
  source text not null default 'rates_proxy_phase1',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, market_mode, window_start, window_end)
);

create table if not exists public.rate_region_health (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  status text not null check (status in ('good', 'partial', 'missing')),
  last_updated_at timestamptz,
  window_start timestamptz not null,
  window_end timestamptz not null,
  expected_hours integer not null default 0,
  missing_hours integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, window_start, window_end)
);

create table if not exists public.rate_project_series (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  market_mode text not null check (market_mode in ('real_time', 'day_ahead', 'tariff')),
  ts timestamptz not null,
  resolution_minutes integer not null default 60,
  value double precision,
  is_forecast boolean not null default false,
  is_modeled boolean not null default false,
  source text,
  source_url text,
  status text not null default 'provisional' check (status in ('provisional', 'final', 'corrected')),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, market_mode, resolution_minutes, ts)
);

create table if not exists public.rate_backfill_jobs (
  project_id text primary key references public.projects(id) on delete cascade,
  status text not null default 'queued' check (status in ('idle', 'queued', 'running', 'completed', 'failed', 'cancelled')),
  lat double precision,
  lng double precision,
  region_id text,
  backfill_start timestamptz,
  backfill_end timestamptz,
  total_tasks integer not null default 0,
  completed_tasks integer not null default 0,
  progress_pct integer not null default 0,
  started_at timestamptz,
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  error text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists weather_cache_project_dataset_idx
  on public.weather_cache (project_id, provider, dataset, fetched_at desc);

create index if not exists weather_cache_payload_gin_idx
  on public.weather_cache using gin (payload);

create index if not exists rate_series_cache_lookup_idx
  on public.rate_series_cache (project_id, region_id, service_type, market_mode, fetched_at desc);

create index if not exists rate_series_cache_payload_gin_idx
  on public.rate_series_cache using gin (payload);

create index if not exists rate_region_health_lookup_idx
  on public.rate_region_health (project_id, region_id, service_type, updated_at desc);

create index if not exists rate_project_series_lookup_idx
  on public.rate_project_series (project_id, region_id, service_type, market_mode, resolution_minutes, ts);

create index if not exists rate_project_series_payload_idx
  on public.rate_project_series (project_id, ts desc);

alter table public.projects enable row level security;
alter table public.assets enable row level security;
alter table public.weather_cache enable row level security;
alter table public.rate_series_cache enable row level security;
alter table public.rate_region_health enable row level security;
alter table public.rate_project_series enable row level security;
alter table public.rate_backfill_jobs enable row level security;

drop policy if exists projects_anon_all on public.projects;
create policy projects_anon_all on public.projects
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists assets_anon_all on public.assets;
create policy assets_anon_all on public.assets
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists weather_cache_anon_all on public.weather_cache;
create policy weather_cache_anon_all on public.weather_cache
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_series_cache_anon_all on public.rate_series_cache;
create policy rate_series_cache_anon_all on public.rate_series_cache
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_region_health_anon_all on public.rate_region_health;
create policy rate_region_health_anon_all on public.rate_region_health
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_project_series_anon_all on public.rate_project_series;
create policy rate_project_series_anon_all on public.rate_project_series
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_backfill_jobs_anon_all on public.rate_backfill_jobs;
create policy rate_backfill_jobs_anon_all on public.rate_backfill_jobs
  for all
  to anon
  using (true)
  with check (true);
