create extension if not exists pgcrypto;

create table if not exists public.projects (
  id text primary key,
  name text not null,
  location_lat double precision,
  location_lng double precision,
  selected_date text,
  weather_provider text,
  utility_name text,
  utility_code text,
  iso_region text,
  timezone text,
  map_state jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assets (
  id text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  asset_type text not null check (asset_type in ('solar', 'wind', 'storage')),
  name text,
  model jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weather_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  provider text not null default 'nrel' check (provider in ('nrel', 'open_meteo')),
  dataset text not null check (dataset in ('solar', 'wind')),
  date_key text not null,
  source_year integer,
  interval_minutes integer not null default 30 check (interval_minutes > 0),
  wkt text,
  timezone text,
  source text not null default 'weather_proxy',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, provider, dataset, date_key, interval_minutes, source_year)
);

create table if not exists public.load_profiles (
  id text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  name text not null,
  model jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists weather_cache_lookup_idx
  on public.weather_cache (project_id, provider, dataset, date_key, fetched_at desc);

create index if not exists weather_cache_payload_gin_idx
  on public.weather_cache using gin (payload);

create index if not exists load_profiles_project_updated_idx
  on public.load_profiles (project_id, updated_at desc);

alter table public.projects enable row level security;
alter table public.assets enable row level security;
alter table public.weather_cache enable row level security;
alter table public.load_profiles enable row level security;

drop policy if exists projects_anon_all on public.projects;
create policy projects_anon_all on public.projects
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists assets_anon_all on public.assets;
create policy assets_anon_all on public.assets
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists weather_cache_anon_all on public.weather_cache;
create policy weather_cache_anon_all on public.weather_cache
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists load_profiles_anon_all on public.load_profiles;
create policy load_profiles_anon_all on public.load_profiles
  for all
  to anon
  using (true)
  with check (true);
