-- EnergyApp bootstrap schema for Supabase/Postgres.
-- Intentionally configured for public, anon/no-auth CRUD.

create table if not exists public.projects (
  id text primary key,
  name text not null default 'Untitled Facility',
  location_lat double precision,
  location_lng double precision,
  selected_date text,
  weather_provider text check (weather_provider in ('nrel', 'open_meteo')),
  map_state jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assets (
  id text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  asset_type text not null check (asset_type in ('solar', 'wind')),
  name text not null default '',
  model jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nrel_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  provider text not null default 'nrel' check (provider in ('nrel', 'open_meteo')),
  dataset text not null check (dataset in ('solar', 'wind')),
  date_key text not null,
  source_year integer,
  interval_minutes integer not null,
  wkt text,
  timezone text,
  source text not null default 'nrel_proxy',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, provider, dataset, date_key, interval_minutes, source_year)
);

create index if not exists nrel_cache_project_dataset_idx
  on public.nrel_cache (project_id, provider, dataset, fetched_at desc);

create index if not exists nrel_cache_payload_gin_idx
  on public.nrel_cache using gin (payload);

alter table public.projects enable row level security;
alter table public.assets enable row level security;
alter table public.nrel_cache enable row level security;

drop policy if exists projects_anon_all on public.projects;
create policy projects_anon_all on public.projects
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists assets_anon_all on public.assets;
create policy assets_anon_all on public.assets
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists nrel_cache_anon_all on public.nrel_cache;
create policy nrel_cache_anon_all on public.nrel_cache
  for all
  to anon
  using (true)
  with check (true);
