alter table public.projects
  add column if not exists utility_name text,
  add column if not exists iso_region text,
  add column if not exists timezone text,
  add column if not exists rates_service_type text check (rates_service_type in ('lmp', 'tariff')),
  add column if not exists rates_market_mode text check (rates_market_mode in ('real_time', 'day_ahead', 'tariff'));

create table if not exists public.rate_series_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  market_mode text not null check (market_mode in ('real_time', 'day_ahead', 'tariff')),
  window_start timestamptz not null,
  window_end timestamptz not null,
  timezone text,
  source text not null default 'rates_proxy_phase1',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, market_mode, window_start, window_end)
);

create table if not exists public.rate_region_health (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  status text not null check (status in ('good', 'partial', 'missing')),
  last_updated_at timestamptz,
  window_start timestamptz not null,
  window_end timestamptz not null,
  expected_hours integer not null default 0,
  missing_hours integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, window_start, window_end)
);

create index if not exists rate_series_cache_lookup_idx
  on public.rate_series_cache (project_id, region_id, service_type, market_mode, fetched_at desc);

create index if not exists rate_series_cache_payload_gin_idx
  on public.rate_series_cache using gin (payload);

create index if not exists rate_region_health_lookup_idx
  on public.rate_region_health (project_id, region_id, service_type, updated_at desc);

alter table public.rate_series_cache enable row level security;
alter table public.rate_region_health enable row level security;

drop policy if exists rate_series_cache_anon_all on public.rate_series_cache;
create policy rate_series_cache_anon_all on public.rate_series_cache
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_region_health_anon_all on public.rate_region_health;
create policy rate_region_health_anon_all on public.rate_region_health
  for all
  to anon
  using (true)
  with check (true);
