create table if not exists public.rate_project_series (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  region_id text not null,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  market_mode text not null check (market_mode in ('real_time', 'day_ahead', 'tariff')),
  ts timestamptz not null,
  resolution_minutes integer not null default 60,
  value double precision,
  is_forecast boolean not null default false,
  is_modeled boolean not null default false,
  source text,
  source_url text,
  status text not null default 'provisional' check (status in ('provisional', 'final', 'corrected')),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, region_id, service_type, market_mode, resolution_minutes, ts)
);

create table if not exists public.rate_backfill_jobs (
  project_id text primary key references public.projects(id) on delete cascade,
  status text not null default 'queued' check (status in ('idle', 'queued', 'running', 'completed', 'failed', 'cancelled')),
  lat double precision,
  lng double precision,
  region_id text,
  backfill_start timestamptz,
  backfill_end timestamptz,
  total_tasks integer not null default 0,
  completed_tasks integer not null default 0,
  progress_pct integer not null default 0,
  started_at timestamptz,
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  error text,
  details jsonb not null default '{}'::jsonb
);

create index if not exists rate_project_series_lookup_idx
  on public.rate_project_series (project_id, region_id, service_type, market_mode, resolution_minutes, ts);

create index if not exists rate_project_series_payload_idx
  on public.rate_project_series (project_id, ts desc);

alter table public.rate_project_series enable row level security;
alter table public.rate_backfill_jobs enable row level security;

drop policy if exists rate_project_series_anon_all on public.rate_project_series;
create policy rate_project_series_anon_all on public.rate_project_series
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists rate_backfill_jobs_anon_all on public.rate_backfill_jobs;
create policy rate_backfill_jobs_anon_all on public.rate_backfill_jobs
  for all
  to anon
  using (true)
  with check (true);

