create table if not exists public.rate_sync_chunks (
  id bigint generated by default as identity primary key,
  job_id uuid references public.ingestion_jobs(id) on delete cascade,
  project_id text not null references public.projects(id) on delete cascade,
  service_type text not null check (service_type in ('lmp', 'tariff')),
  market_mode text not null check (market_mode in ('real_time', 'day_ahead', 'tariff')),
  resolution_minutes integer not null check (resolution_minutes > 0),
  chunk_start timestamptz not null,
  chunk_end timestamptz not null,
  expected_points integer not null default 0,
  completed_points integer not null default 0,
  status text not null default 'queued' check (status in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique nulls not distinct (job_id, project_id, service_type, market_mode, chunk_start, chunk_end)
);

create index if not exists rate_sync_chunks_project_idx
  on public.rate_sync_chunks (project_id, service_type, market_mode, updated_at desc);

create index if not exists rate_sync_chunks_job_idx
  on public.rate_sync_chunks (job_id, status, updated_at desc);

alter table public.rate_sync_chunks enable row level security;

drop policy if exists rate_sync_chunks_anon_all on public.rate_sync_chunks;
create policy rate_sync_chunks_anon_all on public.rate_sync_chunks
  for all
  to anon
  using (true)
  with check (true);
