-- Persist NREL weather payloads with traceability metadata and a stable cache key.
create table if not exists public.nrel_cache (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  dataset text not null check (dataset in ('solar', 'wind')),
  date_key text not null,
  source_year integer not null,
  interval_minutes integer not null,
  wkt text,
  timezone text,
  source text not null default 'nrel_proxy',
  fetched_at timestamptz not null default now(),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, dataset, date_key, source_year, interval_minutes)
);

create index if not exists nrel_cache_project_dataset_idx
  on public.nrel_cache (project_id, dataset, fetched_at desc);

create index if not exists nrel_cache_payload_gin_idx
  on public.nrel_cache using gin (payload);
