-- V3 sync schema for Supabase-only domain persistence.

alter table public.projects
  add column if not exists weather_fingerprint text,
  add column if not exists asset_fingerprint text,
  add column if not exists rates_source_fingerprint text,
  add column if not exists last_login_sync_at timestamptz,
  add column if not exists last_nightly_sync_at timestamptz;

create table if not exists public.weather_project_series (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  provider text not null check (provider in ('nrel', 'open_meteo')),
  dataset text not null check (dataset in ('solar', 'wind')),
  ts timestamptz not null,
  resolution_minutes integer not null check (resolution_minutes > 0),
  is_forecast boolean not null default false,
  metrics jsonb not null default '{}'::jsonb,
  source text,
  fetched_at timestamptz not null default now(),
  status text not null default 'provisional' check (status in ('provisional', 'final')),
  weather_fingerprint text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, provider, dataset, resolution_minutes, ts)
);

create table if not exists public.generation_project_series (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  ts timestamptz not null,
  resolution_minutes integer not null check (resolution_minutes > 0),
  solar_value double precision,
  wind_value double precision,
  total_value double precision,
  unit text not null check (unit in ('kW', 'kWh')),
  is_forecast boolean not null default false,
  status text not null default 'provisional' check (status in ('provisional', 'final')),
  weather_fingerprint text not null,
  asset_fingerprint text not null,
  location_fingerprint text not null,
  computed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, resolution_minutes, ts)
);

create table if not exists public.domain_sync_state (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  domain text not null check (domain in ('weather', 'generation', 'rates', 'storage')),
  rolling_start timestamptz,
  rolling_end timestamptz,
  last_success_at timestamptz,
  last_attempt_at timestamptz,
  last_error text,
  fingerprint text,
  updated_at timestamptz not null default now(),
  unique nulls not distinct (project_id, domain)
);

create table if not exists public.ingestion_jobs (
  id uuid primary key default gen_random_uuid(),
  project_id text not null references public.projects(id) on delete cascade,
  domain text not null check (domain in ('weather', 'generation', 'rates', 'storage')),
  mode text not null check (mode in ('rolling', 'full', 'visible_window')),
  status text not null default 'queued' check (status in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  priority integer not null default 100,
  requested_by text not null check (requested_by in ('user_login', 'manual_refresh', 'nightly_cron', 'location_change', 'asset_change')),
  window_start timestamptz,
  window_end timestamptz,
  payload jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rate_project_series
  add column if not exists rates_source_fingerprint text,
  add column if not exists quality_status text,
  add column if not exists error_code text;

update public.rate_project_series
set rates_source_fingerprint = coalesce(rates_source_fingerprint, 'unknown');

alter table public.rate_project_series
  alter column rates_source_fingerprint set default 'unknown',
  alter column rates_source_fingerprint set not null;

create index if not exists weather_project_series_lookup_idx
  on public.weather_project_series (project_id, dataset, ts);

create index if not exists weather_project_series_project_ts_idx
  on public.weather_project_series (project_id, ts desc);

create index if not exists generation_project_series_lookup_idx
  on public.generation_project_series (project_id, resolution_minutes, ts);

create index if not exists generation_project_series_project_ts_idx
  on public.generation_project_series (project_id, ts desc);

create index if not exists domain_sync_state_lookup_idx
  on public.domain_sync_state (project_id, domain, updated_at desc);

create index if not exists ingestion_jobs_status_priority_idx
  on public.ingestion_jobs (status, priority, created_at);

create index if not exists ingestion_jobs_project_domain_idx
  on public.ingestion_jobs (project_id, domain, created_at desc);

create index if not exists rate_project_series_source_fp_idx
  on public.rate_project_series (project_id, rates_source_fingerprint, ts desc);

alter table public.weather_project_series enable row level security;
alter table public.generation_project_series enable row level security;
alter table public.domain_sync_state enable row level security;
alter table public.ingestion_jobs enable row level security;

drop policy if exists weather_project_series_anon_all on public.weather_project_series;
create policy weather_project_series_anon_all on public.weather_project_series
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists generation_project_series_anon_all on public.generation_project_series;
create policy generation_project_series_anon_all on public.generation_project_series
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists domain_sync_state_anon_all on public.domain_sync_state;
create policy domain_sync_state_anon_all on public.domain_sync_state
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists ingestion_jobs_anon_all on public.ingestion_jobs;
create policy ingestion_jobs_anon_all on public.ingestion_jobs
  for all
  to anon
  using (true)
  with check (true);
